export interface FieldHelpContent {
  fieldId: string;
  tooltip: string;
  expandedGuidance: string;
  glossaryTermSlug: string | null;
  parentFieldId: string | null;
  isDecomposedField: boolean;
  source: "spreadsheet_comment" | "video_extraction" | "authored";
}

export const FIELD_HELP_CONTENT: FieldHelpContent[] = [
  {
    fieldId: "monthlyAuv",
    tooltip: "Your target monthly gross sales (Average Unit Volume). This is typically found in your franchisor's FDD Item 19 financial performance representation.",
    expandedGuidance: "TODO: Extract from Loom video content — Gross Sales / AUV video covers how to find this number in the FDD and what factors affect it.",
    glossaryTermSlug: "auv",
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "timeToReachAuv",
    tooltip: "The number of months it will take to reach Average Unit Volume (AUV) from the start of business operations. Most new franchises take 12-24 months to reach full revenue potential.",
    expandedGuidance: "TODO: Extract from Loom video content — Time to Reach AUV video explains ramp-up patterns and how to estimate conservatively.",
    glossaryTermSlug: "auv",
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "startingMonthAuvPct",
    tooltip: "The estimated percentage of monthly AUV that the business is expected to achieve in the first month of operations. A typical starting point is 40-60% depending on the industry.",
    expandedGuidance: "TODO: Extract from Loom video content — Starting Month AUV % video covers realistic first-month expectations.",
    glossaryTermSlug: "auv",
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "year1GrowthRate",
    tooltip: "Please be aware that the Time to Reach AUV (months) takes precedence over the annual growth rate. After AUV is reached, this growth rate drives year-over-year revenue increases.",
    expandedGuidance: "TODO: Extract from Loom video content — Annual Growth Rate video explains the interaction between AUV ramp and growth rate.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "year2GrowthRate",
    tooltip: "Annual revenue growth rate applied after AUV is reached. The Time to Reach AUV setting takes precedence until AUV is achieved.",
    expandedGuidance: "TODO: Extract from Loom video content — Annual Growth Rate video explains post-AUV growth assumptions.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "corporationTax",
    tooltip: "The federal corporate tax rate applied to pre-tax income. The standard rate is 21%. Adjust only if your business structure or state taxes require a different rate.",
    expandedGuidance: "The standard US federal corporate tax rate is 21%, which applies to C-corporations. S-corporations, LLCs, and sole proprietorships pass income through to the owner's personal tax return at their individual rate. For most franchise financial models, 21% is the correct default. Adjust if your business structure uses pass-through taxation or if you need to account for combined state and federal rates.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "ebitdaMultiple",
    tooltip: "How much buyers typically pay for a business relative to its EBITDA. This varies by industry — common range is 2x to 5x for franchise businesses.",
    expandedGuidance: "TODO: Extract from Loom video content — EBITDA Multiple video explains valuation concepts and typical multiples by industry.",
    glossaryTermSlug: "ebitda-multiple",
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "royaltyPct",
    tooltip: "The ongoing royalty fee paid to the franchisor, expressed as a percentage of gross revenue. This is specified in your franchise agreement.",
    expandedGuidance: "TODO: Extract from Loom video content — Franchise Fees video explains royalty structures and how they impact profitability.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "adFundPct",
    tooltip: "The required advertising/marketing fund contribution to the franchisor, expressed as a percentage of gross revenue. This is in addition to any discretionary marketing you do.",
    expandedGuidance: "TODO: Extract from Loom video content — Franchise Fees video covers ad fund requirements and total marketing spend targets.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "cogsPct",
    tooltip: "Cost of Goods Sold as a percentage of gross revenue. This covers direct materials — the physical goods or supplies consumed in delivering your product or service.",
    expandedGuidance: "TODO: Extract from Loom video content — Materials COGS video covers how to estimate material costs and typical ranges by industry.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "laborPct",
    tooltip: "Gross wages of direct employees as a percentage of gross revenues. Direct means anyone who spends more than 50% of their time on revenue-producing activities. Do not include payroll taxes and benefits here.",
    expandedGuidance: "TODO: Extract from Loom video content — Direct Labor Cost video explains the distinction between direct and indirect labor and why payroll taxes are separate.",
    glossaryTermSlug: "direct-labor-cost",
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "managementSalaries",
    tooltip: "Gross wages of non-direct employees — anyone who spends less than 50% of their time on revenue-producing activities. Includes owner salary, general manager, and admin staff.",
    expandedGuidance: "TODO: Extract from Loom video content — Management & Admin Salaries video covers role-based compensation planning.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "rentMonthly",
    tooltip: "Your monthly lease payment for the franchise location. Check your lease agreement or get an estimate from your broker.",
    expandedGuidance: "Rent is typically the largest single facilities cost. Consider negotiating favorable lease terms, especially for the first year. Some landlords offer rent abatement or graduated increases.",
    glossaryTermSlug: "facilities",
    parentFieldId: "facilities",
    isDecomposedField: true,
    source: "authored",
  },
  {
    fieldId: "utilitiesMonthly",
    tooltip: "Electric, gas, water, and sewer costs. Ask the landlord or previous tenant for typical monthly costs at this location.",
    expandedGuidance: "Utility costs vary significantly by location, climate, and business type. Restaurants and food service businesses typically have higher utility costs than service businesses.",
    glossaryTermSlug: "facilities",
    parentFieldId: "facilities",
    isDecomposedField: true,
    source: "authored",
  },
  {
    fieldId: "insuranceMonthly",
    tooltip: "Property insurance, general liability, and workers' compensation. Your franchisor may have recommended carriers with estimated costs.",
    expandedGuidance: "Insurance requirements vary by franchise brand and location. Contact your franchisor for recommended coverage levels and carrier options. Workers' comp rates depend on your state and industry classification.",
    glossaryTermSlug: null,
    parentFieldId: "facilities",
    isDecomposedField: true,
    source: "authored",
  },
  {
    fieldId: "telecomMonthly",
    tooltip: "Phone lines, internet service, POS system subscriptions, and any software you'll need to run the business.",
    expandedGuidance: "Many franchise systems require specific POS systems and software subscriptions. Check your franchise agreement for required technology and associated monthly costs.",
    glossaryTermSlug: "facilities",
    parentFieldId: "facilities",
    isDecomposedField: true,
    source: "authored",
  },
  {
    fieldId: "vehicleFleetMonthly",
    tooltip: "If your franchise uses vehicles (delivery, service calls), include lease payments, fuel, and maintenance. Skip if not applicable.",
    expandedGuidance: "Vehicle fleet costs only apply to service-based or delivery-based franchise models. If your franchise operates from a fixed location without delivery, this can be left at zero.",
    glossaryTermSlug: "facilities",
    parentFieldId: "facilities",
    isDecomposedField: true,
    source: "authored",
  },
  {
    fieldId: "payrollTaxPct",
    tooltip: "Payroll taxes, health and other insurances, retirement benefits and other ancillary benefits. Expressed as a percentage of total wages (direct labor + management salaries).",
    expandedGuidance: "TODO: Extract from Loom video content — Payroll Taxes & Benefits video covers typical employer burden rates and benefit packages.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "marketingPct",
    tooltip: "Advertising, marketing materials, marketing consultants, ad words, meals & entertainment. Your target total marketing spend (including the ad fund) should be 6-10% of gross sales.",
    expandedGuidance: "TODO: Extract from Loom video content — Marketing video covers discretionary vs. required marketing spend and optimal allocation strategies.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "otherMonthly",
    tooltip: "Other operating expenses — a catchall bucket for everything else not categorized above, such as office supplies, professional services, and miscellaneous costs.",
    expandedGuidance: "TODO: Extract from Loom video content — Other Operating Expenses video covers what typically falls into this category and how to estimate it.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "shareholderSalaryAdj",
    tooltip: "The amount the owner is 'underpaid' relative to market rate for their role. This represents sweat equity — the value of unpaid labor invested in the business.",
    expandedGuidance: "TODO: Extract from Loom video content — Shareholder Salary Adjustment video explains the concept of sweat equity and how it affects true business profitability analysis.",
    glossaryTermSlug: "shareholder-salary-adjustment",
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "totalInvestment",
    tooltip: "Total investment required for a franchise unit, including CapEx, Non-CapEx, and Working Capital. This should match the range provided in your FDD Item 7.",
    expandedGuidance: "TODO: Extract from Loom video content — Total Investment Spending video covers investment categories and how to validate against FDD Item 7.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "capexInvestments",
    tooltip: "Investment into fixed assets that are subject to depreciation — equipment, fixtures, leasehold improvements, and other tangible assets.",
    expandedGuidance: "CapEx investments are depreciated over time, which affects your P&L through depreciation expense and your balance sheet through accumulated depreciation.",
    glossaryTermSlug: null,
    parentFieldId: "totalInvestment",
    isDecomposedField: true,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "nonCapexInvestments",
    tooltip: "Other investments that do not have a tangible asset value — franchise fees, training costs, permits, and initial inventory.",
    expandedGuidance: "Non-CapEx investments are expensed rather than depreciated. They reduce your initial cash but don't create a depreciable asset on the balance sheet.",
    glossaryTermSlug: null,
    parentFieldId: "totalInvestment",
    isDecomposedField: true,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "workingCapital",
    tooltip: "Additional funds and cash available in the business to cover operating expenses during the startup phase before revenue ramps up.",
    expandedGuidance: "Working capital acts as a buffer to cover expenses while the business builds toward profitability. Inadequate working capital is one of the most common reasons new franchises struggle.",
    glossaryTermSlug: null,
    parentFieldId: "totalInvestment",
    isDecomposedField: true,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "equityCashInjection",
    tooltip: "Cash invested by owners or partners — not borrowed money. Additional equity or cash injection can be added post start of operations if needed.",
    expandedGuidance: "TODO: Extract from Loom video content — Equity/Debt video covers financing sources and the equity vs. debt decision.",
    glossaryTermSlug: "equity-cash",
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "loanAmount",
    tooltip: "Total amount borrowed to fund the franchise investment. SBA loans are the most common financing option for franchise purchases.",
    expandedGuidance: "TODO: Extract from Loom video content — Equity/Debt video covers SBA loan structures and alternative financing options.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "loanTermMonths",
    tooltip: "How long your loan term is in months. SBA loans are typically 10 years (120 months).",
    expandedGuidance: "Longer loan terms reduce monthly payments but increase total interest paid. SBA 7(a) loans for franchise purchases typically range from 7 to 25 years depending on the use of funds.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "interestRate",
    tooltip: "Your expected annual interest rate. SBA loans are typically around 10-10.5% as of current rates.",
    expandedGuidance: "SBA loan rates are based on the prime rate plus a spread. Rates vary based on loan size, term, and lender. Shop multiple SBA-approved lenders for the best rate.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "downPaymentPct",
    tooltip: "The percentage of total investment funded by your own equity (down payment). SBA loans typically require 10-20% down.",
    expandedGuidance: "Your down payment comes from your equity sources — personal savings, partner contributions, or other non-borrowed funds. A larger down payment reduces your loan amount and monthly debt service.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "authored",
  },
  {
    fieldId: "distributions",
    tooltip: "Amounts of money taken out of the business by owners or partners. Be cautious about taking distributions before building adequate core capital (at least 2 months of operating expenses).",
    expandedGuidance: "TODO: Extract from Loom video content — Distributions video covers when it's safe to take distributions and how they affect cash reserves and ROIC.",
    glossaryTermSlug: "estimated-distributions",
    parentFieldId: null,
    isDecomposedField: false,
    source: "spreadsheet_comment",
  },
  {
    fieldId: "targetPreTaxProfitPct",
    tooltip: "Your target pre-tax profit as a percentage of revenue. This benchmark helps assess whether your plan meets your financial goals.",
    expandedGuidance: "The target pre-tax profit percentage varies by industry and business maturity. Your franchisor may provide guidance on what healthy margins look like for their system.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "authored",
  },
  {
    fieldId: "depreciationYears",
    tooltip: "The number of years over which your capital expenditures (CapEx) are depreciated. A standard rate is 5-7 years for most franchise equipment and improvements.",
    expandedGuidance: "Depreciation spreads the cost of capital investments over their useful life. This is a non-cash expense that reduces taxable income but doesn't affect actual cash flow.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "authored",
  },
  {
    fieldId: "workingCapitalMonths",
    tooltip: "Number of months of operating expenses to hold in reserve as working capital. A common recommendation is 2-3 months.",
    expandedGuidance: "Working capital reserves ensure you can cover expenses during slow periods or unexpected costs. The appropriate reserve level depends on your business's revenue predictability.",
    glossaryTermSlug: "core-capital",
    parentFieldId: null,
    isDecomposedField: false,
    source: "authored",
  },
  {
    fieldId: "arDays",
    tooltip: "Average number of days to collect payment from customers (Accounts Receivable Days). For cash-based businesses, this is typically 0-5 days.",
    expandedGuidance: "AR Days affect your cash conversion cycle. Businesses that invoice customers (B2B services) typically have 30-60 day collection periods, while retail and restaurant businesses collect immediately.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "authored",
  },
  {
    fieldId: "apDays",
    tooltip: "Average number of days you take to pay your suppliers (Accounts Payable Days). Typical range is 15-45 days.",
    expandedGuidance: "Longer AP days improve your cash position by delaying payments, but may strain supplier relationships. Many franchises have established payment terms with approved vendors.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "authored",
  },
  {
    fieldId: "inventoryDays",
    tooltip: "Average number of days of inventory you keep on hand. Service businesses may have minimal inventory; retail and food businesses need more.",
    expandedGuidance: "Inventory days affect both your cash flow and balance sheet. Too much inventory ties up cash; too little risks stockouts. Your franchisor may recommend optimal inventory levels.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "authored",
  },
  {
    fieldId: "taxPaymentDelay",
    tooltip: "Number of months between when taxes are accrued and when they are actually paid. Typically 3-6 months depending on your tax payment schedule.",
    expandedGuidance: "Tax payment delay affects your cash flow timing. Businesses typically accrue tax expense monthly but pay quarterly or annually, creating a temporary cash benefit.",
    glossaryTermSlug: null,
    parentFieldId: null,
    isDecomposedField: false,
    source: "authored",
  },
];

export const FIELD_HELP_MAP: Map<string, FieldHelpContent> = new Map(
  FIELD_HELP_CONTENT.map((item) => [item.fieldId, item])
);
