name: dev-story
description: "Implement a story using its acceptance criteria and dev notes as authoritative context, with the agent planning its own approach"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "$REPLIT_USER"
communication_language: "$LANG:English"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "$LANG:English"
story_dir: "{config_source}:implementation_artifacts"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-story"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

story_file: "" # Explicit story path; auto-discovered if empty
implementation_artifacts: "{config_source}:implementation_artifacts"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
project_context: "**/project-context.md"
